// Opentrons 24 Tube Rack (Acrylic) with Eppendorf 2 mL Safe-Lock Snapcap
// loadName: opentrons_24_tuberack_eppendorf_2ml_safelock_snapcap_acrylic
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4800, 52.0000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well D1
    translate([15.2800, 13.9000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well C1
    translate([15.2800, 33.4000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well B1
    translate([15.2800, 52.9000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well A1
    translate([15.2800, 72.4000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well D2
    translate([34.7800, 13.9000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well C2
    translate([34.7800, 33.4000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well B2
    translate([34.7800, 52.9000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well A2
    translate([34.7800, 72.4000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well D3
    translate([54.2800, 13.9000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well C3
    translate([54.2800, 33.4000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well B3
    translate([54.2800, 52.9000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well A3
    translate([54.2800, 72.4000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well D4
    translate([73.7800, 13.9000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well C4
    translate([73.7800, 33.4000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well B4
    translate([73.7800, 52.9000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well A4
    translate([73.7800, 72.4000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well D5
    translate([93.2800, 13.9000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well C5
    translate([93.2800, 33.4000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well B5
    translate([93.2800, 52.9000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well A5
    translate([93.2800, 72.4000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well D6
    translate([112.7800, 13.9000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well C6
    translate([112.7800, 33.4000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well B6
    translate([112.7800, 52.9000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
    // Well A6
    translate([112.7800, 72.4000, 13.4200])
        cylinder(h=39.5800, r=4.9500, $fn=$fn);
}