// Opentrons 96 Deep Well Heater-Shaker Adapter
// loadName: opentrons_96_deep_well_adapter
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 32;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([114.2000, 78.2000, 17.5500]);

    // ── Well cutouts ──────────────────────────────────────────────
}