// Opentrons 24 Well Aluminum Block with NEST 2 mL Snapcap
// loadName: opentrons_24_aluminumblock_nest_2ml_snapcap
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7500, 85.5000, 43.6000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([20.7500, 68.6200, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well B1
    translate([20.7500, 51.3700, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well C1
    translate([20.7500, 34.1200, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well D1
    translate([20.7500, 16.8700, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well A2
    translate([38.0000, 68.6200, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well B2
    translate([38.0000, 51.3700, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well C2
    translate([38.0000, 34.1200, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well D2
    translate([38.0000, 16.8700, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well A3
    translate([55.2500, 68.6200, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well B3
    translate([55.2500, 51.3700, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well C3
    translate([55.2500, 34.1200, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well D3
    translate([55.2500, 16.8700, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well A4
    translate([72.5000, 68.6200, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well B4
    translate([72.5000, 51.3700, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well C4
    translate([72.5000, 34.1200, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well D4
    translate([72.5000, 16.8700, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well A5
    translate([89.7500, 68.6200, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well B5
    translate([89.7500, 51.3700, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well C5
    translate([89.7500, 34.1200, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well D5
    translate([89.7500, 16.8700, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well A6
    translate([107.0000, 68.6200, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well B6
    translate([107.0000, 51.3700, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well C6
    translate([107.0000, 34.1200, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
    // Well D6
    translate([107.0000, 16.8700, 4.3200]) union() {
        translate([0, 0, 15.0400])
            cylinder(h=24.2400, r1=4.4500, r2=4.6400, $fn=$fn);
        translate([0, 0, 6.2600])
            cylinder(h=8.7800, r1=4.3700, r2=4.4500, $fn=$fn);
        translate([0, 0, 3.9800])
            cylinder(h=2.2800, r1=4.0000, r2=4.3700, $fn=$fn);
        translate([0, 0, 2.7400])
            cylinder(h=1.2400, r1=3.6000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.5900])
            cylinder(h=0.1500, r1=3.5000, r2=3.6000, $fn=$fn);
        translate([0, 0, 1.8300])
            cylinder(h=0.7600, r1=3.0000, r2=3.5000, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6200, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=4.6400, r2=4.6400, $fn=$fn);
        translate([0, 0, 39.2800])
            cylinder(h=1, r=4.6400, $fn=$fn);
    }
}