// Opentrons 96 Flat Bottom Heater-Shaker Adapter
// loadName: opentrons_96_flat_bottom_adapter
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 32;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([111.0000, 75.0000, 7.9000]);

    // ── Well cutouts ──────────────────────────────────────────────
}