// Corning 96 Wellplate 360ul Lid
// loadName: corning_96_wellplate_360ul_lid
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 32;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.0000, 85.0000, 10.0000]);

    // ── Well cutouts ──────────────────────────────────────────────
}