// Opentrons Flex EV Resin Tips Short Adapter for Third-party Evotips
// loadName: ev_resin_tips_flex_short_adapter
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([130.5000, 98.0000, 51.5000]);

    // ── Well cutouts ──────────────────────────────────────────────
}