[metadata]
name = jubilee-labware
version = 0.1.0
description = Labware library for Science Jubilee experiments
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
url = https://github.com/Jubilee-CSL/labware

[options]
packages = find:
python_requires = >=3.8
install_requires =
    numpy

[options.package_data]
jubilee_labware =
    labware_definition/*/*.json

[options.entry_points]
science_jubilee.labware_dirs =
    jubilee_labware = jubilee_labware:LABWARE_DEFINITION_DIR

[options.extras_require]
stl =
    # OpenSCAD is a system install
