[metadata]
name = jubilee-labware
version = 0.1.0
description = Labware library for Science Jubilee experiments
long_description = file: README.md
long_description_content_type = text/markdown
license = MIT
url = https://github.com/Jubilee-CSL/science-jubilee-interface

[options]
packages = jubilee_labware
python_requires = >=3.8
install_requires =
    numpy

[options.package_data]
jubilee_labware =
    labware_definition/*/*.json
