// NEST 8 Well Reservoir 22 mL
// loadName: nest_8_reservoir_22ml
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4800, 31.4000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([10.1300, 70.1400, 4.5500])
        cube([107.5000, 8.2000, 27.8500]);
    // Well B1
    translate([10.1300, 61.1400, 4.5500])
        cube([107.5000, 8.2000, 27.8500]);
    // Well C1
    translate([10.1300, 52.1400, 4.5500])
        cube([107.5000, 8.2000, 27.8500]);
    // Well D1
    translate([10.1300, 43.1400, 4.5500])
        cube([107.5000, 8.2000, 27.8500]);
    // Well E1
    translate([10.1300, 34.1400, 4.5500])
        cube([107.5000, 8.2000, 27.8500]);
    // Well F1
    translate([10.1300, 25.1400, 4.5500])
        cube([107.5000, 8.2000, 27.8500]);
    // Well G1
    translate([10.1300, 16.1400, 4.5500])
        cube([107.5000, 8.2000, 27.8500]);
    // Well H1
    translate([10.1300, 7.1400, 4.5500])
        cube([107.5000, 8.2000, 27.8500]);
}