// glass of water 250 mL
// loadName: glass_250ml
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 32;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([85.0000, 85.0000, 90.0000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([40.0000, 40.0000, 5.0000])
        cylinder(h=86.0000, r=37.5000, $fn=$fn);
}