// Opentrons Tough 22mL 12 Well Reservoir
// loadName: opentrons_tough_12_reservoir_22ml
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4800, 45.3000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([10.2800, 7.3900, 3.0000])
        cube([8.2000, 70.7000, 43.3000]);
    // Well A2
    translate([19.2800, 7.3900, 3.0000])
        cube([8.2000, 70.7000, 43.3000]);
    // Well A3
    translate([28.2800, 7.3900, 3.0000])
        cube([8.2000, 70.7000, 43.3000]);
    // Well A4
    translate([37.2800, 7.3900, 3.0000])
        cube([8.2000, 70.7000, 43.3000]);
    // Well A5
    translate([46.2800, 7.3900, 3.0000])
        cube([8.2000, 70.7000, 43.3000]);
    // Well A6
    translate([55.2800, 7.3900, 3.0000])
        cube([8.2000, 70.7000, 43.3000]);
    // Well A7
    translate([64.2800, 7.3900, 3.0000])
        cube([8.2000, 70.7000, 43.3000]);
    // Well A8
    translate([73.2800, 7.3900, 3.0000])
        cube([8.2000, 70.7000, 43.3000]);
    // Well A9
    translate([82.2800, 7.3900, 3.0000])
        cube([8.2000, 70.7000, 43.3000]);
    // Well A10
    translate([91.2800, 7.3900, 3.0000])
        cube([8.2000, 70.7000, 43.3000]);
    // Well A11
    translate([100.2800, 7.3900, 3.0000])
        cube([8.2000, 70.7000, 43.3000]);
    // Well A12
    translate([109.2800, 7.3900, 3.0000])
        cube([8.2000, 70.7000, 43.3000]);
}