// NEST 1 Well Reservoir 195 mL
// loadName: nest_1_reservoir_195ml
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4800, 31.4000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([28.2300, -10.9100, 4.5500])
        cube([71.3000, 107.3000, 27.8500]);
}