// Opentrons 24 Well Aluminum Block with NEST 1.5 mL Snapcap
// loadName: opentrons_24_aluminumblock_nest_1.5ml_snapcap
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7500, 85.5000, 43.7000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([20.7500, 68.6200, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well B1
    translate([20.7500, 51.3700, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well C1
    translate([20.7500, 34.1200, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well D1
    translate([20.7500, 16.8700, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well A2
    translate([38.0000, 68.6200, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well B2
    translate([38.0000, 51.3700, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well C2
    translate([38.0000, 34.1200, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well D2
    translate([38.0000, 16.8700, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well A3
    translate([55.2500, 68.6200, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well B3
    translate([55.2500, 51.3700, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well C3
    translate([55.2500, 34.1200, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well D3
    translate([55.2500, 16.8700, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well A4
    translate([72.5000, 68.6200, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well B4
    translate([72.5000, 51.3700, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well C4
    translate([72.5000, 34.1200, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well D4
    translate([72.5000, 16.8700, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well A5
    translate([89.7500, 68.6200, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well B5
    translate([89.7500, 51.3700, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well C5
    translate([89.7500, 34.1200, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well D5
    translate([89.7500, 16.8700, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well A6
    translate([107.0000, 68.6200, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well B6
    translate([107.0000, 51.3700, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well C6
    translate([107.0000, 34.1200, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
    // Well D6
    translate([107.0000, 16.8700, 5.8000]) union() {
        translate([0, 0, 35.4000])
            cylinder(h=2.5000, r1=4.6400, r2=4.9500, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=18.0000, r1=4.4900, r2=4.6400, $fn=$fn);
        translate([0, 0, 1.5600])
            cylinder(h=15.8400, r1=1.8450, r2=4.4900, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.5600, r1=4.9500, r2=4.9500, $fn=$fn);
        translate([0, 0, 37.9000])
            cylinder(h=1, r=4.9500, $fn=$fn);
    }
}