// Opentrons 96 Deep Well Temperature Module Adapter
// loadName: opentrons_96_deep_well_temp_mod_adapter
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 32;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7500, 85.5000, 21.4000]);

    // ── Well cutouts ──────────────────────────────────────────────
}