// Opentrons Calibration Block - Short Side: Right
// loadName: opentrons_calibrationblock_short_side_right
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7500, 85.5000, 62.5000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([0.0000, 0.0000, 62.5000])
        cube([63.8800, 85.5000, 1.0000]);
    // Well A2
    translate([63.8700, 0.0000, 33.0000])
        cube([63.8800, 85.5000, 1.0000]);
}