// USA Scientific 12 Well Reservoir 22 mL
// loadName: usascientific_12_reservoir_22ml
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.8000, 44.2000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([9.7815, 6.9600, 2.4500])
        cube([8.3170, 71.8800, 42.7500]);
    // Well A2
    translate([18.8715, 6.9600, 2.4500])
        cube([8.3170, 71.8800, 42.7500]);
    // Well A3
    translate([27.9615, 6.9600, 2.4500])
        cube([8.3170, 71.8800, 42.7500]);
    // Well A4
    translate([37.0515, 6.9600, 2.4500])
        cube([8.3170, 71.8800, 42.7500]);
    // Well A5
    translate([46.1415, 6.9600, 2.4500])
        cube([8.3170, 71.8800, 42.7500]);
    // Well A6
    translate([55.2315, 6.9600, 2.4500])
        cube([8.3170, 71.8800, 42.7500]);
    // Well A7
    translate([64.3215, 6.9600, 2.4500])
        cube([8.3170, 71.8800, 42.7500]);
    // Well A8
    translate([73.4115, 6.9600, 2.4500])
        cube([8.3170, 71.8800, 42.7500]);
    // Well A9
    translate([82.5015, 6.9600, 2.4500])
        cube([8.3170, 71.8800, 42.7500]);
    // Well A10
    translate([91.5915, 6.9600, 2.4500])
        cube([8.3170, 71.8800, 42.7500]);
    // Well A11
    translate([100.6815, 6.9600, 2.4500])
        cube([8.3170, 71.8800, 42.7500]);
    // Well A12
    translate([109.7715, 6.9600, 2.4500])
        cube([8.3170, 71.8800, 42.7500]);
}