// ibidi 96 Square Well Flat Bottom Plate 300 µL Lid
// loadName: ibidi_96_square_well_plate_300ul_lid
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 32;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.0000, 84.5000, 6.9500]);

    // ── Well cutouts ──────────────────────────────────────────────
}