// Corning 24 Well Plate 3.4 mL Flat
// loadName: corning_24_wellplate_3.4ml_flat
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4700, 20.2700]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well D1
    translate([17.4800, 13.7700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well C1
    translate([17.4800, 33.0700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well B1
    translate([17.4800, 52.3700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well A1
    translate([17.4800, 71.6700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well D2
    translate([36.7800, 13.7700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well C2
    translate([36.7800, 33.0700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well B2
    translate([36.7800, 52.3700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well A2
    translate([36.7800, 71.6700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well D3
    translate([56.0800, 13.7700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well C3
    translate([56.0800, 33.0700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well B3
    translate([56.0800, 52.3700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well A3
    translate([56.0800, 71.6700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well D4
    translate([75.3800, 13.7700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well C4
    translate([75.3800, 33.0700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well B4
    translate([75.3800, 52.3700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well A4
    translate([75.3800, 71.6700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well D5
    translate([94.6800, 13.7700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well C5
    translate([94.6800, 33.0700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well B5
    translate([94.6800, 52.3700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well A5
    translate([94.6800, 71.6700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well D6
    translate([113.9800, 13.7700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well C6
    translate([113.9800, 33.0700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well B6
    translate([113.9800, 52.3700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
    // Well A6
    translate([113.9800, 71.6700, 2.8700]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=7.8105, r2=8.1280, $fn=$fn);
        translate([0, 0, 17.4000])
            cylinder(h=1, r=8.1280, $fn=$fn);
    }
}