// Bio-Rad 96 Well Plate 200 µL PCR
// loadName: biorad_96_wellplate_200ul_pcr
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 8;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4800, 16.0600]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well H1
    translate([14.3800, 11.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well G1
    translate([14.3800, 20.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well F1
    translate([14.3800, 29.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well E1
    translate([14.3800, 38.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well D1
    translate([14.3800, 47.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well C1
    translate([14.3800, 56.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well B1
    translate([14.3800, 65.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well A1
    translate([14.3800, 74.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well H2
    translate([23.3800, 11.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well G2
    translate([23.3800, 20.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well F2
    translate([23.3800, 29.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well E2
    translate([23.3800, 38.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well D2
    translate([23.3800, 47.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well C2
    translate([23.3800, 56.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well B2
    translate([23.3800, 65.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well A2
    translate([23.3800, 74.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well H3
    translate([32.3800, 11.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well G3
    translate([32.3800, 20.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well F3
    translate([32.3800, 29.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well E3
    translate([32.3800, 38.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well D3
    translate([32.3800, 47.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well C3
    translate([32.3800, 56.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well B3
    translate([32.3800, 65.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well A3
    translate([32.3800, 74.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well H4
    translate([41.3800, 11.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well G4
    translate([41.3800, 20.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well F4
    translate([41.3800, 29.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well E4
    translate([41.3800, 38.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well D4
    translate([41.3800, 47.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well C4
    translate([41.3800, 56.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well B4
    translate([41.3800, 65.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well A4
    translate([41.3800, 74.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well H5
    translate([50.3800, 11.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well G5
    translate([50.3800, 20.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well F5
    translate([50.3800, 29.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well E5
    translate([50.3800, 38.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well D5
    translate([50.3800, 47.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well C5
    translate([50.3800, 56.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well B5
    translate([50.3800, 65.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well A5
    translate([50.3800, 74.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well H6
    translate([59.3800, 11.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well G6
    translate([59.3800, 20.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well F6
    translate([59.3800, 29.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well E6
    translate([59.3800, 38.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well D6
    translate([59.3800, 47.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well C6
    translate([59.3800, 56.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well B6
    translate([59.3800, 65.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well A6
    translate([59.3800, 74.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well H7
    translate([68.3800, 11.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well G7
    translate([68.3800, 20.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well F7
    translate([68.3800, 29.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well E7
    translate([68.3800, 38.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well D7
    translate([68.3800, 47.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well C7
    translate([68.3800, 56.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well B7
    translate([68.3800, 65.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well A7
    translate([68.3800, 74.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well H8
    translate([77.3800, 11.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well G8
    translate([77.3800, 20.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well F8
    translate([77.3800, 29.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well E8
    translate([77.3800, 38.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well D8
    translate([77.3800, 47.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well C8
    translate([77.3800, 56.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well B8
    translate([77.3800, 65.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well A8
    translate([77.3800, 74.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well H9
    translate([86.3800, 11.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well G9
    translate([86.3800, 20.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well F9
    translate([86.3800, 29.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well E9
    translate([86.3800, 38.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well D9
    translate([86.3800, 47.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well C9
    translate([86.3800, 56.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well B9
    translate([86.3800, 65.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well A9
    translate([86.3800, 74.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well H10
    translate([95.3800, 11.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well G10
    translate([95.3800, 20.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well F10
    translate([95.3800, 29.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well E10
    translate([95.3800, 38.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well D10
    translate([95.3800, 47.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well C10
    translate([95.3800, 56.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well B10
    translate([95.3800, 65.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well A10
    translate([95.3800, 74.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well H11
    translate([104.3800, 11.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well G11
    translate([104.3800, 20.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well F11
    translate([104.3800, 29.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well E11
    translate([104.3800, 38.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well D11
    translate([104.3800, 47.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well C11
    translate([104.3800, 56.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well B11
    translate([104.3800, 65.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well A11
    translate([104.3800, 74.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well H12
    translate([113.3800, 11.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well G12
    translate([113.3800, 20.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well F12
    translate([113.3800, 29.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well E12
    translate([113.3800, 38.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well D12
    translate([113.3800, 47.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well C12
    translate([113.3800, 56.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well B12
    translate([113.3800, 65.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
    // Well A12
    translate([113.3800, 74.2400, 1.2500]) union() {
        translate([0, 0, 10.1400])
            cylinder(h=4.4300, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 8.5800])
            cylinder(h=1.5600, r1=2.4900, r2=2.7200, $fn=$fn);
        translate([0, 0, 1.8700])
            cylinder(h=6.7100, r1=1.5000, r2=2.4900, $fn=$fn);
        translate([0, 0, 1.2100])
            cylinder(h=0.6600, r1=1.4050, r2=1.5000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.2100, r1=2.7200, r2=2.7200, $fn=$fn);
        translate([0, 0, 14.5700])
            cylinder(h=1, r=2.7200, $fn=$fn);
    }
}