// Lid Stack
// loadName: protocol_engine_lid_stack_object
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([0.0000, 0.0000, 0.0000]);

    // ── Well cutouts ──────────────────────────────────────────────
}