// Opentrons Tough 72 mL 4 Well Reservoir
// loadName: opentrons_tough_4_reservoir_72ml
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4800, 45.3000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([9.5250, 7.3900, 3.0000])
        cube([26.4300, 70.7000, 43.3000]);
    // Well A2
    translate([36.9550, 7.3900, 3.0000])
        cube([26.4300, 70.7000, 43.3000]);
    // Well A3
    translate([64.3850, 7.3900, 3.0000])
        cube([26.4300, 70.7000, 43.3000]);
    // Well A4
    translate([91.8150, 7.3900, 3.0000])
        cube([26.4300, 70.7000, 43.3000]);
}