// Opentrons 15 Tube Rack with Falcon 15 mL Conical
// loadName: opentrons_15_tuberack_falcon_15ml_conical
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4800, 124.3500]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well C1
    translate([13.8800, 17.7400, 6.8500]) union() {
        translate([0, 0, 108.6000])
            cylinder(h=9.6000, r1=7.2500, r2=7.3500, $fn=$fn);
        translate([0, 0, 20.7000])
            cylinder(h=87.9000, r1=6.7500, r2=7.2500, $fn=$fn);
        translate([0, 0, 0.8000])
            cylinder(h=19.9000, r1=2.0000, r2=6.7500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.8000, r1=7.3500, r2=7.3500, $fn=$fn);
        translate([0, 0, 117.5000])
            cylinder(h=1, r=7.3500, $fn=$fn);
    }
    // Well B1
    translate([13.8800, 42.7400, 6.8500]) union() {
        translate([0, 0, 108.6000])
            cylinder(h=9.6000, r1=7.2500, r2=7.3500, $fn=$fn);
        translate([0, 0, 20.7000])
            cylinder(h=87.9000, r1=6.7500, r2=7.2500, $fn=$fn);
        translate([0, 0, 0.8000])
            cylinder(h=19.9000, r1=2.0000, r2=6.7500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.8000, r1=7.3500, r2=7.3500, $fn=$fn);
        translate([0, 0, 117.5000])
            cylinder(h=1, r=7.3500, $fn=$fn);
    }
    // Well A1
    translate([13.8800, 67.7400, 6.8500]) union() {
        translate([0, 0, 108.6000])
            cylinder(h=9.6000, r1=7.2500, r2=7.3500, $fn=$fn);
        translate([0, 0, 20.7000])
            cylinder(h=87.9000, r1=6.7500, r2=7.2500, $fn=$fn);
        translate([0, 0, 0.8000])
            cylinder(h=19.9000, r1=2.0000, r2=6.7500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.8000, r1=7.3500, r2=7.3500, $fn=$fn);
        translate([0, 0, 117.5000])
            cylinder(h=1, r=7.3500, $fn=$fn);
    }
    // Well C2
    translate([38.8800, 17.7400, 6.8500]) union() {
        translate([0, 0, 108.6000])
            cylinder(h=9.6000, r1=7.2500, r2=7.3500, $fn=$fn);
        translate([0, 0, 20.7000])
            cylinder(h=87.9000, r1=6.7500, r2=7.2500, $fn=$fn);
        translate([0, 0, 0.8000])
            cylinder(h=19.9000, r1=2.0000, r2=6.7500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.8000, r1=7.3500, r2=7.3500, $fn=$fn);
        translate([0, 0, 117.5000])
            cylinder(h=1, r=7.3500, $fn=$fn);
    }
    // Well B2
    translate([38.8800, 42.7400, 6.8500]) union() {
        translate([0, 0, 108.6000])
            cylinder(h=9.6000, r1=7.2500, r2=7.3500, $fn=$fn);
        translate([0, 0, 20.7000])
            cylinder(h=87.9000, r1=6.7500, r2=7.2500, $fn=$fn);
        translate([0, 0, 0.8000])
            cylinder(h=19.9000, r1=2.0000, r2=6.7500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.8000, r1=7.3500, r2=7.3500, $fn=$fn);
        translate([0, 0, 117.5000])
            cylinder(h=1, r=7.3500, $fn=$fn);
    }
    // Well A2
    translate([38.8800, 67.7400, 6.8500]) union() {
        translate([0, 0, 108.6000])
            cylinder(h=9.6000, r1=7.2500, r2=7.3500, $fn=$fn);
        translate([0, 0, 20.7000])
            cylinder(h=87.9000, r1=6.7500, r2=7.2500, $fn=$fn);
        translate([0, 0, 0.8000])
            cylinder(h=19.9000, r1=2.0000, r2=6.7500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.8000, r1=7.3500, r2=7.3500, $fn=$fn);
        translate([0, 0, 117.5000])
            cylinder(h=1, r=7.3500, $fn=$fn);
    }
    // Well C3
    translate([63.8800, 17.7400, 6.8500]) union() {
        translate([0, 0, 108.6000])
            cylinder(h=9.6000, r1=7.2500, r2=7.3500, $fn=$fn);
        translate([0, 0, 20.7000])
            cylinder(h=87.9000, r1=6.7500, r2=7.2500, $fn=$fn);
        translate([0, 0, 0.8000])
            cylinder(h=19.9000, r1=2.0000, r2=6.7500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.8000, r1=7.3500, r2=7.3500, $fn=$fn);
        translate([0, 0, 117.5000])
            cylinder(h=1, r=7.3500, $fn=$fn);
    }
    // Well B3
    translate([63.8800, 42.7400, 6.8500]) union() {
        translate([0, 0, 108.6000])
            cylinder(h=9.6000, r1=7.2500, r2=7.3500, $fn=$fn);
        translate([0, 0, 20.7000])
            cylinder(h=87.9000, r1=6.7500, r2=7.2500, $fn=$fn);
        translate([0, 0, 0.8000])
            cylinder(h=19.9000, r1=2.0000, r2=6.7500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.8000, r1=7.3500, r2=7.3500, $fn=$fn);
        translate([0, 0, 117.5000])
            cylinder(h=1, r=7.3500, $fn=$fn);
    }
    // Well A3
    translate([63.8800, 67.7400, 6.8500]) union() {
        translate([0, 0, 108.6000])
            cylinder(h=9.6000, r1=7.2500, r2=7.3500, $fn=$fn);
        translate([0, 0, 20.7000])
            cylinder(h=87.9000, r1=6.7500, r2=7.2500, $fn=$fn);
        translate([0, 0, 0.8000])
            cylinder(h=19.9000, r1=2.0000, r2=6.7500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.8000, r1=7.3500, r2=7.3500, $fn=$fn);
        translate([0, 0, 117.5000])
            cylinder(h=1, r=7.3500, $fn=$fn);
    }
    // Well C4
    translate([88.8800, 17.7400, 6.8500]) union() {
        translate([0, 0, 108.6000])
            cylinder(h=9.6000, r1=7.2500, r2=7.3500, $fn=$fn);
        translate([0, 0, 20.7000])
            cylinder(h=87.9000, r1=6.7500, r2=7.2500, $fn=$fn);
        translate([0, 0, 0.8000])
            cylinder(h=19.9000, r1=2.0000, r2=6.7500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.8000, r1=7.3500, r2=7.3500, $fn=$fn);
        translate([0, 0, 117.5000])
            cylinder(h=1, r=7.3500, $fn=$fn);
    }
    // Well B4
    translate([88.8800, 42.7400, 6.8500]) union() {
        translate([0, 0, 108.6000])
            cylinder(h=9.6000, r1=7.2500, r2=7.3500, $fn=$fn);
        translate([0, 0, 20.7000])
            cylinder(h=87.9000, r1=6.7500, r2=7.2500, $fn=$fn);
        translate([0, 0, 0.8000])
            cylinder(h=19.9000, r1=2.0000, r2=6.7500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.8000, r1=7.3500, r2=7.3500, $fn=$fn);
        translate([0, 0, 117.5000])
            cylinder(h=1, r=7.3500, $fn=$fn);
    }
    // Well A4
    translate([88.8800, 67.7400, 6.8500]) union() {
        translate([0, 0, 108.6000])
            cylinder(h=9.6000, r1=7.2500, r2=7.3500, $fn=$fn);
        translate([0, 0, 20.7000])
            cylinder(h=87.9000, r1=6.7500, r2=7.2500, $fn=$fn);
        translate([0, 0, 0.8000])
            cylinder(h=19.9000, r1=2.0000, r2=6.7500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.8000, r1=7.3500, r2=7.3500, $fn=$fn);
        translate([0, 0, 117.5000])
            cylinder(h=1, r=7.3500, $fn=$fn);
    }
    // Well C5
    translate([113.8800, 17.7400, 6.8500]) union() {
        translate([0, 0, 108.6000])
            cylinder(h=9.6000, r1=7.2500, r2=7.3500, $fn=$fn);
        translate([0, 0, 20.7000])
            cylinder(h=87.9000, r1=6.7500, r2=7.2500, $fn=$fn);
        translate([0, 0, 0.8000])
            cylinder(h=19.9000, r1=2.0000, r2=6.7500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.8000, r1=7.3500, r2=7.3500, $fn=$fn);
        translate([0, 0, 117.5000])
            cylinder(h=1, r=7.3500, $fn=$fn);
    }
    // Well B5
    translate([113.8800, 42.7400, 6.8500]) union() {
        translate([0, 0, 108.6000])
            cylinder(h=9.6000, r1=7.2500, r2=7.3500, $fn=$fn);
        translate([0, 0, 20.7000])
            cylinder(h=87.9000, r1=6.7500, r2=7.2500, $fn=$fn);
        translate([0, 0, 0.8000])
            cylinder(h=19.9000, r1=2.0000, r2=6.7500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.8000, r1=7.3500, r2=7.3500, $fn=$fn);
        translate([0, 0, 117.5000])
            cylinder(h=1, r=7.3500, $fn=$fn);
    }
    // Well A5
    translate([113.8800, 67.7400, 6.8500]) union() {
        translate([0, 0, 108.6000])
            cylinder(h=9.6000, r1=7.2500, r2=7.3500, $fn=$fn);
        translate([0, 0, 20.7000])
            cylinder(h=87.9000, r1=6.7500, r2=7.2500, $fn=$fn);
        translate([0, 0, 0.8000])
            cylinder(h=19.9000, r1=2.0000, r2=6.7500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.8000, r1=7.3500, r2=7.3500, $fn=$fn);
        translate([0, 0, 117.5000])
            cylinder(h=1, r=7.3500, $fn=$fn);
    }
}