// Black 96-well Microtiter Plate Lid
// loadName: black_96_well_microtiter_plate_lid
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 32;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.5000, 85.0000, 10.0000]);

    // ── Well cutouts ──────────────────────────────────────────────
}