// Opentrons Aluminum Flat Bottom Plate
// loadName: opentrons_aluminum_flat_bottom_plate
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([134.0000, 92.0000, 11.2000]);

    // ── Well cutouts ──────────────────────────────────────────────
}