// NEST 12 Well Reservoir 22 mL
// loadName: nest_12_reservoir_22ml
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4800, 44.4000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([10.2800, 7.1400, 4.8500])
        cube([8.2000, 71.2000, 40.5500]);
    // Well A2
    translate([19.2800, 7.1400, 4.8500])
        cube([8.2000, 71.2000, 40.5500]);
    // Well A3
    translate([28.2800, 7.1400, 4.8500])
        cube([8.2000, 71.2000, 40.5500]);
    // Well A4
    translate([37.2800, 7.1400, 4.8500])
        cube([8.2000, 71.2000, 40.5500]);
    // Well A5
    translate([46.2800, 7.1400, 4.8500])
        cube([8.2000, 71.2000, 40.5500]);
    // Well A6
    translate([55.2800, 7.1400, 4.8500])
        cube([8.2000, 71.2000, 40.5500]);
    // Well A7
    translate([64.2800, 7.1400, 4.8500])
        cube([8.2000, 71.2000, 40.5500]);
    // Well A8
    translate([73.2800, 7.1400, 4.8500])
        cube([8.2000, 71.2000, 40.5500]);
    // Well A9
    translate([82.2800, 7.1400, 4.8500])
        cube([8.2000, 71.2000, 40.5500]);
    // Well A10
    translate([91.2800, 7.1400, 4.8500])
        cube([8.2000, 71.2000, 40.5500]);
    // Well A11
    translate([100.2800, 7.1400, 4.8500])
        cube([8.2000, 71.2000, 40.5500]);
    // Well A12
    translate([109.2800, 7.1400, 4.8500])
        cube([8.2000, 71.2000, 40.5500]);
}