// Opentrons 24 Tube Rack with Eppendorf 2 mL Safe-Lock Snapcap
// loadName: opentrons_24_tuberack_eppendorf_2ml_safelock_snapcap
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7500, 85.5000, 79.8500]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well D1
    translate([18.2100, 17.5900, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well C1
    translate([18.2100, 36.8700, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well B1
    translate([18.2100, 56.1500, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well A1
    translate([18.2100, 75.4300, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well D2
    translate([38.1000, 17.5900, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well C2
    translate([38.1000, 36.8700, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well B2
    translate([38.1000, 56.1500, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well A2
    translate([38.1000, 75.4300, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well D3
    translate([57.9900, 17.5900, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well C3
    translate([57.9900, 36.8700, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well B3
    translate([57.9900, 56.1500, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well A3
    translate([57.9900, 75.4300, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well D4
    translate([77.8800, 17.5900, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well C4
    translate([77.8800, 36.8700, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well B4
    translate([77.8800, 56.1500, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well A4
    translate([77.8800, 75.4300, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well D5
    translate([97.7700, 17.5900, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well C5
    translate([97.7700, 36.8700, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well B5
    translate([97.7700, 56.1500, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well A5
    translate([97.7700, 75.4300, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well D6
    translate([117.6600, 17.5900, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well C6
    translate([117.6600, 36.8700, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well B6
    translate([117.6600, 56.1500, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well A6
    translate([117.6600, 75.4300, 41.2700]) union() {
        translate([0, 0, 33.9600])
            cylinder(h=5.0600, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 32.5000])
            cylinder(h=1.4600, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 25.2600])
            cylinder(h=7.2400, r1=4.5500, r2=4.6000, $fn=$fn);
        translate([0, 0, 13.3200])
            cylinder(h=11.9400, r1=4.5000, r2=4.5500, $fn=$fn);
        translate([0, 0, 10.1700])
            cylinder(h=3.1500, r1=4.4500, r2=4.5000, $fn=$fn);
        translate([0, 0, 6.9700])
            cylinder(h=3.2000, r1=4.3900, r2=4.4500, $fn=$fn);
        translate([0, 0, 5.4300])
            cylinder(h=1.5400, r1=4.3000, r2=4.3900, $fn=$fn);
        translate([0, 0, 5.1500])
            cylinder(h=0.2800, r1=4.2500, r2=4.3000, $fn=$fn);
        translate([0, 0, 5.0300])
            cylinder(h=0.1200, r1=4.2000, r2=4.2500, $fn=$fn);
        translate([0, 0, 4.5300])
            cylinder(h=0.5000, r1=4.1000, r2=4.2000, $fn=$fn);
        translate([0, 0, 4.2900])
            cylinder(h=0.2400, r1=4.0000, r2=4.1000, $fn=$fn);
        translate([0, 0, 3.9300])
            cylinder(h=0.3600, r1=3.8500, r2=4.0000, $fn=$fn);
        translate([0, 0, 3.6700])
            cylinder(h=0.2600, r1=3.8000, r2=3.8500, $fn=$fn);
        translate([0, 0, 3.1400])
            cylinder(h=0.5300, r1=3.6000, r2=3.8000, $fn=$fn);
        translate([0, 0, 2.7500])
            cylinder(h=0.3900, r1=3.4000, r2=3.6000, $fn=$fn);
        translate([0, 0, 2.4500])
            cylinder(h=0.3000, r1=3.2000, r2=3.4000, $fn=$fn);
        translate([0, 0, 2.2000])
            cylinder(h=0.2500, r1=3.0000, r2=3.2000, $fn=$fn);
        translate([0, 0, 1.4500])
            cylinder(h=0.7500, r1=2.5000, r2=3.0000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=1.4500, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 39.1000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
}