// Opentrons 24 Well Aluminum Block with NEST 1.5 mL Screwcap
// loadName: opentrons_24_aluminumblock_nest_1.5ml_screwcap
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7500, 85.5000, 49.3500]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([20.7500, 68.6200, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well B1
    translate([20.7500, 51.3700, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well C1
    translate([20.7500, 34.1200, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well D1
    translate([20.7500, 16.8700, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well A2
    translate([38.0000, 68.6200, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well B2
    translate([38.0000, 51.3700, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well C2
    translate([38.0000, 34.1200, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well D2
    translate([38.0000, 16.8700, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well A3
    translate([55.2500, 68.6200, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well B3
    translate([55.2500, 51.3700, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well C3
    translate([55.2500, 34.1200, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well D3
    translate([55.2500, 16.8700, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well A4
    translate([72.5000, 68.6200, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well B4
    translate([72.5000, 51.3700, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well C4
    translate([72.5000, 34.1200, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well D4
    translate([72.5000, 16.8700, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well A5
    translate([89.7500, 68.6200, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well B5
    translate([89.7500, 51.3700, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well C5
    translate([89.7500, 34.1200, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well D5
    translate([89.7500, 16.8700, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well A6
    translate([107.0000, 68.6200, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well B6
    translate([107.0000, 51.3700, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well C6
    translate([107.0000, 34.1200, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
    // Well D6
    translate([107.0000, 16.8700, 5.4500]) union() {
        translate([0, 0, 13.7000])
            cylinder(h=28.9000, r1=4.1000, r2=4.2750, $fn=$fn);
        translate([0, 0, 1.8800])
            cylinder(h=11.8200, r1=1.6000, r2=4.1000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=1.6800, r1=0.9500, r2=1.6000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=4.2750, r2=4.2750, $fn=$fn);
        translate([0, 0, 43.9000])
            cylinder(h=1, r=4.2750, $fn=$fn);
    }
}