// Agilent 1 Well Reservoir 290 mL
// loadName: agilent_1_reservoir_290ml
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.5700, 44.0400]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([10.1300, 7.1600, 4.8100])
        cube([107.5000, 71.2500, 40.2300]);
}