// Opentrons 24 Well Aluminum Block with Generic 2 mL Screwcap
// loadName: opentrons_24_aluminumblock_generic_2ml_screwcap
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7500, 85.5000, 48.7000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well D1
    translate([20.7500, 16.8800, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well C1
    translate([20.7500, 34.1300, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well B1
    translate([20.7500, 51.3800, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well A1
    translate([20.7500, 68.6300, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well D2
    translate([38.0000, 16.8800, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well C2
    translate([38.0000, 34.1300, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well B2
    translate([38.0000, 51.3800, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well A2
    translate([38.0000, 68.6300, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well D3
    translate([55.2500, 16.8800, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well C3
    translate([55.2500, 34.1300, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well B3
    translate([55.2500, 51.3800, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well A3
    translate([55.2500, 68.6300, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well D4
    translate([72.5000, 16.8800, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well C4
    translate([72.5000, 34.1300, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well B4
    translate([72.5000, 51.3800, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well A4
    translate([72.5000, 68.6300, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well D5
    translate([89.7500, 16.8800, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well C5
    translate([89.7500, 34.1300, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well B5
    translate([89.7500, 51.3800, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well A5
    translate([89.7500, 68.6300, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well D6
    translate([107.0000, 16.8800, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well C6
    translate([107.0000, 34.1300, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well B6
    translate([107.0000, 51.3800, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
    // Well A6
    translate([107.0000, 68.6300, 6.7000]) union() {
        translate([0, 0, 3.0400])
            cylinder(h=38.9600, r1=4.0700, r2=4.2500, $fn=$fn);
        translate([0, 0, 2.0800])
            cylinder(h=0.9600, r1=3.2500, r2=4.0700, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.0800, r1=0.6050, r2=3.2500, $fn=$fn);
        translate([0, 0, 42.0000])
            cylinder(h=1, r=3.2500, $fn=$fn);
    }
}