// Corning 12 Well Plate 6.9 mL Flat
// loadName: corning_12_wellplate_6.9ml_flat
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.8900, 85.6000, 20.0200]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well C1
    translate([24.9400, 16.7900, 2.4900]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=11.0490, r2=11.3665, $fn=$fn);
        translate([0, 0, 17.3990])
            cylinder(h=1, r=11.3665, $fn=$fn);
    }
    // Well B1
    translate([24.9400, 42.8000, 2.4900]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=11.0490, r2=11.3665, $fn=$fn);
        translate([0, 0, 17.3990])
            cylinder(h=1, r=11.3665, $fn=$fn);
    }
    // Well A1
    translate([24.9400, 68.8100, 2.4900]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=11.0490, r2=11.3665, $fn=$fn);
        translate([0, 0, 17.3990])
            cylinder(h=1, r=11.3665, $fn=$fn);
    }
    // Well C2
    translate([50.9500, 16.7900, 2.4900]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=11.0490, r2=11.3665, $fn=$fn);
        translate([0, 0, 17.3990])
            cylinder(h=1, r=11.3665, $fn=$fn);
    }
    // Well B2
    translate([50.9500, 42.8000, 2.4900]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=11.0490, r2=11.3665, $fn=$fn);
        translate([0, 0, 17.3990])
            cylinder(h=1, r=11.3665, $fn=$fn);
    }
    // Well A2
    translate([50.9500, 68.8100, 2.4900]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=11.0490, r2=11.3665, $fn=$fn);
        translate([0, 0, 17.3990])
            cylinder(h=1, r=11.3665, $fn=$fn);
    }
    // Well C3
    translate([76.9600, 16.7900, 2.4900]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=11.0490, r2=11.3665, $fn=$fn);
        translate([0, 0, 17.3990])
            cylinder(h=1, r=11.3665, $fn=$fn);
    }
    // Well B3
    translate([76.9600, 42.8000, 2.4900]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=11.0490, r2=11.3665, $fn=$fn);
        translate([0, 0, 17.3990])
            cylinder(h=1, r=11.3665, $fn=$fn);
    }
    // Well A3
    translate([76.9600, 68.8100, 2.4900]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=11.0490, r2=11.3665, $fn=$fn);
        translate([0, 0, 17.3990])
            cylinder(h=1, r=11.3665, $fn=$fn);
    }
    // Well C4
    translate([102.9700, 16.7900, 2.4900]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=11.0490, r2=11.3665, $fn=$fn);
        translate([0, 0, 17.3990])
            cylinder(h=1, r=11.3665, $fn=$fn);
    }
    // Well B4
    translate([102.9700, 42.8000, 2.4900]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=11.0490, r2=11.3665, $fn=$fn);
        translate([0, 0, 17.3990])
            cylinder(h=1, r=11.3665, $fn=$fn);
    }
    // Well A4
    translate([102.9700, 68.8100, 2.4900]) union() {
        translate([0, 0, 0.0000])
            cylinder(h=17.3990, r1=11.0490, r2=11.3665, $fn=$fn);
        translate([0, 0, 17.3990])
            cylinder(h=1, r=11.3665, $fn=$fn);
    }
}