// Opentrons Flex EV Resin Tips Tall Adapter for Third-party Evotips in 96 Tip Rack Adapter
// loadName: ev_resin_tips_flex_96_tiprack_adapter
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 32;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([156.5000, 98.0000, 132.0000]);

    // ── Well cutouts ──────────────────────────────────────────────
}