// Opentrons Tough Universal Lid
// loadName: opentrons_tough_universal_lid
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4800, 9.2000]);

    // ── Well cutouts ──────────────────────────────────────────────
}