// Opentrons 15 Tube Rack with NEST 15 mL Conical
// loadName: opentrons_15_tuberack_nest_15ml_conical
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4800, 124.6500]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([13.8800, 67.7400, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well B1
    translate([13.8800, 42.7400, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well C1
    translate([13.8800, 17.7400, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well A2
    translate([38.8800, 67.7400, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well B2
    translate([38.8800, 42.7400, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well C2
    translate([38.8800, 17.7400, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well A3
    translate([63.8800, 67.7400, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well B3
    translate([63.8800, 42.7400, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well C3
    translate([63.8800, 17.7400, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well A4
    translate([88.8800, 67.7400, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well B4
    translate([88.8800, 42.7400, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well C4
    translate([88.8800, 17.7400, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well A5
    translate([113.8800, 67.7400, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well B5
    translate([113.8800, 42.7400, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well C5
    translate([113.8800, 17.7400, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
}