// Scienfocus 6 Well Plate 15900 µL
// loadName: scienfocus_6_wellplate_15900ul
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.0000, 85.2500, 20.0000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([23.0000, 62.2500, 3.5000])
        cylinder(h=17.5000, r=17.5000, $fn=$fn);
    // Well B1
    translate([23.0000, 23.2500, 3.5000])
        cylinder(h=17.5000, r=17.5000, $fn=$fn);
    // Well A2
    translate([62.0000, 62.2500, 3.5000])
        cylinder(h=17.5000, r=17.5000, $fn=$fn);
    // Well B2
    translate([62.0000, 23.2500, 3.5000])
        cylinder(h=17.5000, r=17.5000, $fn=$fn);
    // Well A3
    translate([101.0000, 62.2500, 3.5000])
        cylinder(h=17.5000, r=17.5000, $fn=$fn);
    // Well B3
    translate([101.0000, 23.2500, 3.5000])
        cylinder(h=17.5000, r=17.5000, $fn=$fn);
}