// Eppendorf 96 Protein LoBind Deepwell Plate 500 µL
// loadName: eppendorf_96_wellplate_500ul_lobind
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 8;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4800, 27.1000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([14.3800, 74.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well B1
    translate([14.3800, 65.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well C1
    translate([14.3800, 56.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well D1
    translate([14.3800, 47.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well E1
    translate([14.3800, 38.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well F1
    translate([14.3800, 29.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well G1
    translate([14.3800, 20.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well H1
    translate([14.3800, 11.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well A2
    translate([23.3800, 74.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well B2
    translate([23.3800, 65.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well C2
    translate([23.3800, 56.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well D2
    translate([23.3800, 47.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well E2
    translate([23.3800, 38.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well F2
    translate([23.3800, 29.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well G2
    translate([23.3800, 20.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well H2
    translate([23.3800, 11.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well A3
    translate([32.3800, 74.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well B3
    translate([32.3800, 65.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well C3
    translate([32.3800, 56.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well D3
    translate([32.3800, 47.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well E3
    translate([32.3800, 38.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well F3
    translate([32.3800, 29.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well G3
    translate([32.3800, 20.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well H3
    translate([32.3800, 11.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well A4
    translate([41.3800, 74.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well B4
    translate([41.3800, 65.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well C4
    translate([41.3800, 56.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well D4
    translate([41.3800, 47.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well E4
    translate([41.3800, 38.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well F4
    translate([41.3800, 29.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well G4
    translate([41.3800, 20.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well H4
    translate([41.3800, 11.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well A5
    translate([50.3800, 74.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well B5
    translate([50.3800, 65.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well C5
    translate([50.3800, 56.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well D5
    translate([50.3800, 47.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well E5
    translate([50.3800, 38.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well F5
    translate([50.3800, 29.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well G5
    translate([50.3800, 20.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well H5
    translate([50.3800, 11.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well A6
    translate([59.3800, 74.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well B6
    translate([59.3800, 65.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well C6
    translate([59.3800, 56.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well D6
    translate([59.3800, 47.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well E6
    translate([59.3800, 38.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well F6
    translate([59.3800, 29.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well G6
    translate([59.3800, 20.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well H6
    translate([59.3800, 11.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well A7
    translate([68.3800, 74.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well B7
    translate([68.3800, 65.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well C7
    translate([68.3800, 56.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well D7
    translate([68.3800, 47.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well E7
    translate([68.3800, 38.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well F7
    translate([68.3800, 29.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well G7
    translate([68.3800, 20.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well H7
    translate([68.3800, 11.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well A8
    translate([77.3800, 74.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well B8
    translate([77.3800, 65.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well C8
    translate([77.3800, 56.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well D8
    translate([77.3800, 47.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well E8
    translate([77.3800, 38.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well F8
    translate([77.3800, 29.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well G8
    translate([77.3800, 20.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well H8
    translate([77.3800, 11.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well A9
    translate([86.3800, 74.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well B9
    translate([86.3800, 65.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well C9
    translate([86.3800, 56.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well D9
    translate([86.3800, 47.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well E9
    translate([86.3800, 38.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well F9
    translate([86.3800, 29.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well G9
    translate([86.3800, 20.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well H9
    translate([86.3800, 11.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well A10
    translate([95.3800, 74.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well B10
    translate([95.3800, 65.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well C10
    translate([95.3800, 56.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well D10
    translate([95.3800, 47.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well E10
    translate([95.3800, 38.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well F10
    translate([95.3800, 29.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well G10
    translate([95.3800, 20.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well H10
    translate([95.3800, 11.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well A11
    translate([104.3800, 74.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well B11
    translate([104.3800, 65.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well C11
    translate([104.3800, 56.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well D11
    translate([104.3800, 47.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well E11
    translate([104.3800, 38.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well F11
    translate([104.3800, 29.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well G11
    translate([104.3800, 20.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well H11
    translate([104.3800, 11.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well A12
    translate([113.3800, 74.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well B12
    translate([113.3800, 65.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well C12
    translate([113.3800, 56.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well D12
    translate([113.3800, 47.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well E12
    translate([113.3800, 38.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well F12
    translate([113.3800, 29.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well G12
    translate([113.3800, 20.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
    // Well H12
    translate([113.3800, 11.2400, 3.1000]) union() {
        translate([0, 0, 14.7200])
            cylinder(h=9.2800, r1=3.5000, r2=3.5000, $fn=$fn);
        translate([0, 0, 12.7800])
            cylinder(h=1.9400, r1=3.4500, r2=3.4500, $fn=$fn);
        translate([0, 0, 10.7100])
            cylinder(h=2.0700, r1=3.3400, r2=3.3400, $fn=$fn);
        translate([0, 0, 8.5600])
            cylinder(h=2.1500, r1=3.2800, r2=3.2800, $fn=$fn);
        translate([0, 0, 6.5800])
            cylinder(h=1.9800, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 4.7600])
            cylinder(h=1.8200, r1=3.2500, r2=3.2500, $fn=$fn);
        translate([0, 0, 2.5800])
            cylinder(h=2.1800, r1=3.3800, r2=3.3800, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.5800, r1=2.4900, r2=2.4900, $fn=$fn);
        translate([0, 0, 24.0000])
            cylinder(h=1, r=2.4900, $fn=$fn);
    }
}