// ThermoFisher Nunc MaxiSorp Lockwell ELISA
// loadName: thermofisher_nunc_maxisorp_lockwell_elisa
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 16;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7000, 85.6000, 14.2000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([14.4000, 74.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well B1
    translate([14.4000, 65.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well C1
    translate([14.4000, 56.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well D1
    translate([14.4000, 47.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well E1
    translate([14.4000, 38.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well F1
    translate([14.4000, 29.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well G1
    translate([14.4000, 20.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well H1
    translate([14.4000, 11.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well A2
    translate([23.4000, 74.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well B2
    translate([23.4000, 65.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well C2
    translate([23.4000, 56.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well D2
    translate([23.4000, 47.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well E2
    translate([23.4000, 38.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well F2
    translate([23.4000, 29.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well G2
    translate([23.4000, 20.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well H2
    translate([23.4000, 11.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well A3
    translate([32.4000, 74.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well B3
    translate([32.4000, 65.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well C3
    translate([32.4000, 56.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well D3
    translate([32.4000, 47.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well E3
    translate([32.4000, 38.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well F3
    translate([32.4000, 29.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well G3
    translate([32.4000, 20.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well H3
    translate([32.4000, 11.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well A4
    translate([41.4000, 74.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well B4
    translate([41.4000, 65.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well C4
    translate([41.4000, 56.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well D4
    translate([41.4000, 47.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well E4
    translate([41.4000, 38.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well F4
    translate([41.4000, 29.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well G4
    translate([41.4000, 20.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well H4
    translate([41.4000, 11.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well A5
    translate([50.4000, 74.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well B5
    translate([50.4000, 65.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well C5
    translate([50.4000, 56.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well D5
    translate([50.4000, 47.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well E5
    translate([50.4000, 38.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well F5
    translate([50.4000, 29.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well G5
    translate([50.4000, 20.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well H5
    translate([50.4000, 11.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well A6
    translate([59.4000, 74.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well B6
    translate([59.4000, 65.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well C6
    translate([59.4000, 56.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well D6
    translate([59.4000, 47.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well E6
    translate([59.4000, 38.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well F6
    translate([59.4000, 29.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well G6
    translate([59.4000, 20.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well H6
    translate([59.4000, 11.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well A7
    translate([68.4000, 74.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well B7
    translate([68.4000, 65.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well C7
    translate([68.4000, 56.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well D7
    translate([68.4000, 47.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well E7
    translate([68.4000, 38.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well F7
    translate([68.4000, 29.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well G7
    translate([68.4000, 20.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well H7
    translate([68.4000, 11.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well A8
    translate([77.4000, 74.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well B8
    translate([77.4000, 65.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well C8
    translate([77.4000, 56.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well D8
    translate([77.4000, 47.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well E8
    translate([77.4000, 38.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well F8
    translate([77.4000, 29.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well G8
    translate([77.4000, 20.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well H8
    translate([77.4000, 11.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well A9
    translate([86.4000, 74.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well B9
    translate([86.4000, 65.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well C9
    translate([86.4000, 56.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well D9
    translate([86.4000, 47.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well E9
    translate([86.4000, 38.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well F9
    translate([86.4000, 29.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well G9
    translate([86.4000, 20.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well H9
    translate([86.4000, 11.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well A10
    translate([95.4000, 74.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well B10
    translate([95.4000, 65.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well C10
    translate([95.4000, 56.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well D10
    translate([95.4000, 47.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well E10
    translate([95.4000, 38.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well F10
    translate([95.4000, 29.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well G10
    translate([95.4000, 20.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well H10
    translate([95.4000, 11.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well A11
    translate([104.4000, 74.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well B11
    translate([104.4000, 65.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well C11
    translate([104.4000, 56.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well D11
    translate([104.4000, 47.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well E11
    translate([104.4000, 38.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well F11
    translate([104.4000, 29.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well G11
    translate([104.4000, 20.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well H11
    translate([104.4000, 11.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well A12
    translate([113.4000, 74.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well B12
    translate([113.4000, 65.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well C12
    translate([113.4000, 56.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well D12
    translate([113.4000, 47.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well E12
    translate([113.4000, 38.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well F12
    translate([113.4000, 29.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well G12
    translate([113.4000, 20.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
    // Well H12
    translate([113.4000, 11.1000, 3.4000]) union() {
        translate([0, 0, 10.0300])
            cylinder(h=0.7700, r1=3.4100, r2=3.3000, $fn=$fn);
        translate([0, 0, 9.6400])
            cylinder(h=0.3900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 8.1500])
            cylinder(h=1.4900, r1=3.6100, r2=3.6100, $fn=$fn);
        translate([0, 0, 6.7500])
            cylinder(h=1.4000, r1=3.3200, r2=3.3200, $fn=$fn);
        translate([0, 0, 5.2300])
            cylinder(h=1.5200, r1=3.2000, r2=3.2000, $fn=$fn);
        translate([0, 0, 3.7500])
            cylinder(h=1.4800, r1=3.2400, r2=3.2400, $fn=$fn);
        translate([0, 0, 2.1900])
            cylinder(h=1.5600, r1=3.1500, r2=3.1500, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=2.1900, r1=3.4100, r2=3.4100, $fn=$fn);
        translate([0, 0, 10.8000])
            cylinder(h=1, r=3.4100, $fn=$fn);
    }
}