// 20ccScintillation_screwdown_vialplate
// loadName: 20ccscintillation_screwdown_vialplate
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4800, 69.0000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([18.8700, 71.0500, 5.0000])
        cylinder(h=65.0000, r=6.0000, $fn=$fn);
    // Well B1
    translate([18.8700, 42.7400, 5.0000])
        cylinder(h=65.0000, r=6.0000, $fn=$fn);
    // Well C1
    translate([18.8700, 14.4300, 5.0000])
        cylinder(h=65.0000, r=6.0000, $fn=$fn);
    // Well A2
    translate([48.8700, 71.0500, 5.0000])
        cylinder(h=65.0000, r=6.0000, $fn=$fn);
    // Well B2
    translate([48.8700, 42.7400, 5.0000])
        cylinder(h=65.0000, r=6.0000, $fn=$fn);
    // Well C2
    translate([48.8700, 14.4300, 5.0000])
        cylinder(h=65.0000, r=6.0000, $fn=$fn);
    // Well A3
    translate([78.8700, 71.0500, 5.0000])
        cylinder(h=65.0000, r=6.0000, $fn=$fn);
    // Well B3
    translate([78.8700, 42.7400, 5.0000])
        cylinder(h=65.0000, r=6.0000, $fn=$fn);
    // Well C3
    translate([78.8700, 14.4300, 5.0000])
        cylinder(h=65.0000, r=6.0000, $fn=$fn);
    // Well A4
    translate([108.8700, 71.0500, 5.0000])
        cylinder(h=65.0000, r=6.0000, $fn=$fn);
    // Well B4
    translate([108.8700, 42.7400, 5.0000])
        cylinder(h=65.0000, r=6.0000, $fn=$fn);
    // Well C4
    translate([108.8700, 14.4300, 5.0000])
        cylinder(h=65.0000, r=6.0000, $fn=$fn);
}