// NEST 1 Well Reservoir 290 mL
// loadName: nest_1_reservoir_290ml
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4700, 44.4000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([10.0000, 7.1900, 4.8500])
        cube([107.7600, 71.1000, 40.5500]);
}