// Opentrons Universal Flat Heater-Shaker Adapter
// loadName: opentrons_universal_flat_adapter
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([111.0000, 75.0000, 12.0000]);

    // ── Well cutouts ──────────────────────────────────────────────
}