// Opentrons Calibration Adapter - Heater-shaker Module
// loadName: opentrons_calibration_adapter_heatershaker_module
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([111.0000, 75.0000, 13.8500]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([45.5000, 27.5000, 9.1000])
        cube([20.0000, 20.0000, 5.7500]);
    // Well B1
    translate([68.5000, 50.5000, 13.8500])
        cylinder(h=1.0000, r=0.5000, $fn=$fn);
}