// Opentrons 24 Tube Rack (Acrylic) with Generic 0.75 mL Snapcap
// loadName: opentrons_24_tuberack_generic_0.75ml_snapcap_acrylic
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4800, 55.0000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well D1
    translate([16.7600, 11.9400, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well C1
    translate([16.7600, 31.5000, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well B1
    translate([16.7600, 51.0600, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well A1
    translate([16.7600, 70.6200, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well D2
    translate([36.3200, 11.9400, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well C2
    translate([36.3200, 31.5000, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well B2
    translate([36.3200, 51.0600, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well A2
    translate([36.3200, 70.6200, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well D3
    translate([55.8800, 11.9400, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well C3
    translate([55.8800, 31.5000, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well B3
    translate([55.8800, 51.0600, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well A3
    translate([55.8800, 70.6200, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well D4
    translate([75.4400, 11.9400, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well C4
    translate([75.4400, 31.5000, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well B4
    translate([75.4400, 51.0600, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well A4
    translate([75.4400, 70.6200, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well D5
    translate([95.0000, 11.9400, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well C5
    translate([95.0000, 31.5000, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well B5
    translate([95.0000, 51.0600, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well A5
    translate([95.0000, 70.6200, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well D6
    translate([114.5600, 11.9400, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well C6
    translate([114.5600, 31.5000, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well B6
    translate([114.5600, 51.0600, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
    // Well A6
    translate([114.5600, 70.6200, 35.0000])
        cylinder(h=21.0000, r=3.0000, $fn=$fn);
}