// Opentrons Calibration Adapter - Temperature Module
// loadName: opentrons_calibration_adapter_temperature_module
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7500, 85.5000, 15.0000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([54.0000, 33.0000, 10.2500])
        cube([20.0000, 20.0000, 5.7500]);
    // Well B1
    translate([77.0000, 56.0000, 15.0000])
        cylinder(h=1.0000, r=0.5000, $fn=$fn);
}