// Opentrons 24 Tube Rack with Eppendorf 1.5 mL Safe-Lock Snapcap
// loadName: opentrons_24_tuberack_eppendorf_1.5ml_safelock_snapcap
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7500, 85.5000, 79.8500]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well D1
    translate([18.2100, 17.5900, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well C1
    translate([18.2100, 36.8700, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well B1
    translate([18.2100, 56.1500, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well A1
    translate([18.2100, 75.4300, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well D2
    translate([38.1000, 17.5900, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well C2
    translate([38.1000, 36.8700, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well B2
    translate([38.1000, 56.1500, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well A2
    translate([38.1000, 75.4300, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well D3
    translate([57.9900, 17.5900, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well C3
    translate([57.9900, 36.8700, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well B3
    translate([57.9900, 56.1500, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well A3
    translate([57.9900, 75.4300, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well D4
    translate([77.8800, 17.5900, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well C4
    translate([77.8800, 36.8700, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well B4
    translate([77.8800, 56.1500, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well A4
    translate([77.8800, 75.4300, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well D5
    translate([97.7700, 17.5900, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well C5
    translate([97.7700, 36.8700, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well B5
    translate([97.7700, 56.1500, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well A5
    translate([97.7700, 75.4300, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well D6
    translate([117.6600, 17.5900, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well C6
    translate([117.6600, 36.8700, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well B6
    translate([117.6600, 56.1500, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
    // Well A6
    translate([117.6600, 75.4300, 42.0500]) union() {
        translate([0, 0, 32.4900])
            cylinder(h=5.3100, r1=4.8000, r2=5.0000, $fn=$fn);
        translate([0, 0, 31.9700])
            cylinder(h=0.5200, r1=4.6000, r2=4.8000, $fn=$fn);
        translate([0, 0, 31.1600])
            cylinder(h=0.8100, r1=4.5100, r2=4.6000, $fn=$fn);
        translate([0, 0, 28.1600])
            cylinder(h=3.0000, r1=4.4500, r2=4.5100, $fn=$fn);
        translate([0, 0, 17.5600])
            cylinder(h=10.6000, r1=4.2500, r2=4.4500, $fn=$fn);
        translate([0, 0, 15.8900])
            cylinder(h=1.6700, r1=4.0000, r2=4.2500, $fn=$fn);
        translate([0, 0, 9.2400])
            cylinder(h=6.6500, r1=3.0000, r2=4.0000, $fn=$fn);
        translate([0, 0, 2.9000])
            cylinder(h=6.3400, r1=2.0000, r2=3.0000, $fn=$fn);
        translate([0, 0, 1.0000])
            cylinder(h=1.9000, r1=1.6300, r2=2.0000, $fn=$fn);
        translate([0, 0, 0.2000])
            cylinder(h=0.8000, r1=1.0000, r2=1.6300, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.2000, r1=5.0000, r2=5.0000, $fn=$fn);
        translate([0, 0, 37.8000])
            cylinder(h=1, r=5.0000, $fn=$fn);
    }
}