// Opentrons 10 Tube Rack with NEST 4x50 mL, 6x15 mL Conical
// loadName: opentrons_10_tuberack_nest_4x50ml_6x15ml_conical
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4800, 124.6500]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well A1
    translate([13.8800, 67.7500, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well B1
    translate([13.8800, 42.7500, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well C1
    translate([13.8800, 17.7500, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well A2
    translate([38.8800, 67.7500, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well B2
    translate([38.8800, 42.7500, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well C2
    translate([38.8800, 17.7500, 6.8500]) union() {
        translate([0, 0, 113.8000])
            cylinder(h=4.0000, r1=7.2800, r2=7.7500, $fn=$fn);
        translate([0, 0, 22.5500])
            cylinder(h=91.2500, r1=6.9000, r2=7.2800, $fn=$fn);
        translate([0, 0, 0.9200])
            cylinder(h=21.6300, r1=1.1900, r2=6.9000, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=0.9200, r1=7.7500, r2=7.7500, $fn=$fn);
        translate([0, 0, 117.8000])
            cylinder(h=1, r=7.7500, $fn=$fn);
    }
    // Well A3
    translate([71.3800, 60.2500, 7.3000]) union() {
        translate([0, 0, 109.1000])
            cylinder(h=4.0000, r1=13.9750, r2=14.0900, $fn=$fn);
        translate([0, 0, 108.8000])
            cylinder(h=0.3000, r1=13.8450, r2=13.9750, $fn=$fn);
        translate([0, 0, 14.3500])
            cylinder(h=94.4500, r1=13.0000, r2=13.8450, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=14.3500, r1=2.2500, r2=13.0000, $fn=$fn);
        translate([0, 0, 113.1000])
            cylinder(h=1, r=13.0000, $fn=$fn);
    }
    // Well B3
    translate([71.3800, 25.2500, 7.3000]) union() {
        translate([0, 0, 109.1000])
            cylinder(h=4.0000, r1=13.9750, r2=14.0900, $fn=$fn);
        translate([0, 0, 108.8000])
            cylinder(h=0.3000, r1=13.8450, r2=13.9750, $fn=$fn);
        translate([0, 0, 14.3500])
            cylinder(h=94.4500, r1=13.0000, r2=13.8450, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=14.3500, r1=2.2500, r2=13.0000, $fn=$fn);
        translate([0, 0, 113.1000])
            cylinder(h=1, r=13.0000, $fn=$fn);
    }
    // Well A4
    translate([106.3800, 60.2500, 7.3000]) union() {
        translate([0, 0, 109.1000])
            cylinder(h=4.0000, r1=13.9750, r2=14.0900, $fn=$fn);
        translate([0, 0, 108.8000])
            cylinder(h=0.3000, r1=13.8450, r2=13.9750, $fn=$fn);
        translate([0, 0, 14.3500])
            cylinder(h=94.4500, r1=13.0000, r2=13.8450, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=14.3500, r1=2.2500, r2=13.0000, $fn=$fn);
        translate([0, 0, 113.1000])
            cylinder(h=1, r=13.0000, $fn=$fn);
    }
    // Well B4
    translate([106.3800, 25.2500, 7.3000]) union() {
        translate([0, 0, 109.1000])
            cylinder(h=4.0000, r1=13.9750, r2=14.0900, $fn=$fn);
        translate([0, 0, 108.8000])
            cylinder(h=0.3000, r1=13.8450, r2=13.9750, $fn=$fn);
        translate([0, 0, 14.3500])
            cylinder(h=94.4500, r1=13.0000, r2=13.8450, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=14.3500, r1=2.2500, r2=13.0000, $fn=$fn);
        translate([0, 0, 113.1000])
            cylinder(h=1, r=13.0000, $fn=$fn);
    }
}