// Opentrons 6 Tube Rack with Falcon 50 mL Conical
// loadName: opentrons_6_tuberack_falcon_50ml_conical
// Auto-generated by labware_to_stl.py from Opentrons V2 labware definition

$fn = 64;

difference() {
    // ── Labware body ──────────────────────────────────────────────
    cube([127.7600, 85.4800, 120.3000]);

    // ── Well cutouts ──────────────────────────────────────────────
    // Well B1
    translate([35.5000, 25.2400, 7.3000]) union() {
        translate([0, 0, 100.6500])
            cylinder(h=12.2000, r1=13.7600, r2=13.9050, $fn=$fn);
        translate([0, 0, 14.3000])
            cylinder(h=86.3500, r1=13.0900, r2=13.7600, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=14.3000, r1=3.0750, r2=13.0900, $fn=$fn);
        translate([0, 0, 113.0000])
            cylinder(h=1, r=13.0900, $fn=$fn);
    }
    // Well A1
    translate([35.5000, 60.2400, 7.3000]) union() {
        translate([0, 0, 100.6500])
            cylinder(h=12.2000, r1=13.7600, r2=13.9050, $fn=$fn);
        translate([0, 0, 14.3000])
            cylinder(h=86.3500, r1=13.0900, r2=13.7600, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=14.3000, r1=3.0750, r2=13.0900, $fn=$fn);
        translate([0, 0, 113.0000])
            cylinder(h=1, r=13.0900, $fn=$fn);
    }
    // Well B2
    translate([70.5000, 25.2400, 7.3000]) union() {
        translate([0, 0, 100.6500])
            cylinder(h=12.2000, r1=13.7600, r2=13.9050, $fn=$fn);
        translate([0, 0, 14.3000])
            cylinder(h=86.3500, r1=13.0900, r2=13.7600, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=14.3000, r1=3.0750, r2=13.0900, $fn=$fn);
        translate([0, 0, 113.0000])
            cylinder(h=1, r=13.0900, $fn=$fn);
    }
    // Well A2
    translate([70.5000, 60.2400, 7.3000]) union() {
        translate([0, 0, 100.6500])
            cylinder(h=12.2000, r1=13.7600, r2=13.9050, $fn=$fn);
        translate([0, 0, 14.3000])
            cylinder(h=86.3500, r1=13.0900, r2=13.7600, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=14.3000, r1=3.0750, r2=13.0900, $fn=$fn);
        translate([0, 0, 113.0000])
            cylinder(h=1, r=13.0900, $fn=$fn);
    }
    // Well B3
    translate([105.5000, 25.2400, 7.3000]) union() {
        translate([0, 0, 100.6500])
            cylinder(h=12.2000, r1=13.7600, r2=13.9050, $fn=$fn);
        translate([0, 0, 14.3000])
            cylinder(h=86.3500, r1=13.0900, r2=13.7600, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=14.3000, r1=3.0750, r2=13.0900, $fn=$fn);
        translate([0, 0, 113.0000])
            cylinder(h=1, r=13.0900, $fn=$fn);
    }
    // Well A3
    translate([105.5000, 60.2400, 7.3000]) union() {
        translate([0, 0, 100.6500])
            cylinder(h=12.2000, r1=13.7600, r2=13.9050, $fn=$fn);
        translate([0, 0, 14.3000])
            cylinder(h=86.3500, r1=13.0900, r2=13.7600, $fn=$fn);
        translate([0, 0, 0.0000])
            cylinder(h=14.3000, r1=3.0750, r2=13.0900, $fn=$fn);
        translate([0, 0, 113.0000])
            cylinder(h=1, r=13.0900, $fn=$fn);
    }
}